### ISSUE TITLE
[FATAL] [1708590121.963867895]: initialize_i2c: Failed to connect to pigpio daemon.

### ISSUE THREAD

**Issue by saqihk** [pcdangio/ros-driver_mpu9250#17]
after going through the installation of pigpio 
i installed pigpio though git because i was'nt able to install it as given commands  
i successfully made catkin also 
then when i ran this command it gave me an error 

[FATAL] [1708590121.963867895]: initialize_i2c: Failed to connect to pigpio daemon.

**Comment by pcdangio** [comment]
It's been a while since I wrote the install instructions, pigpio may have changed its build/install process. I'll take a look and update the instructions as needed. As for fatal error you are getting, it sounds like the pigpio daemon isn't running in the background. Did you start the daemon in the background using the pigpiod command before trying to run your code?
