### ISSUE TITLE
Failed to connect to pigpio daemon

### ISSUE THREAD

**Issue by Farhan996** [pcdangio/ros-driver_mpu9250#7]
Upon running <rosrun driver_mpu9250 driver_mpu9250_rpi> , I'm getting this error

[FATAL] [1614248377.275806757] : Failed to connect to pigpio daemon

**Comment by pcdangio** [comment]
This error happens if you don’t run pigpiod before trying to start the node. The node relies on a running pigpio daemon to handle the actual I/O. You can start up the daemon in another terminal with the command:

`sudo pigpiod`

I listed this in the rpi_node section of the documentation, but I should probably list it in the usage section as well.

**Comment by pcdangio** [comment]
I went ahead and updated the "Usage" section of the README to specify running the PiGPIO daemon.
