### ISSUE TITLE
How can I publish sensor_msgs/Imu ?

### ISSUE THREAD

**Issue by nn10n10** [pcdangio/ros-driver_mpu9250#9]
Hello! I've already published sensor_msgs_ext/accelerometer using this driver, but I'm using robot_localizaiton package witch needs sensor_msgs/Imu. How can I do ? Thanks!

**Comment by pcdangio** [comment]
Hi, if you'd like this driver to output ```sensor_msgs/Imu``` messages, your best bet is to modify the source code (particularly [ros_node.cpp](https://github.com/pcdangio/ros-driver_mpu9250/blob/master/src/ros_node.cpp). The ```ros_node::data_callback()``` method is where the message gets populated and published.

I specifically chose not to use the ```sensor_msgs``` message types because they are inefficient. The ```sensor_msgs_ext``` types I had made split things into different message groups that are easier to manage and transfer necessary data more efficiently.

If you do modify the source code to use ```sensor_msgs/Imu```, I'd be willing to host it as a branch so others can use it when needed. Just let me know!

**Comment by nn10n10** [comment]
> Hi, if you'd like this driver to output `sensor_msgs/Imu` messages, your best bet is to modify the source code (particularly [ros_node.cpp](https://github.com/pcdangio/ros-driver_mpu9250/blob/master/src/ros_node.cpp). The `ros_node::data_callback()` method is where the message gets populated and published.
> 
> I specifically chose not to use the `sensor_msgs` message types because they are inefficient. The `sensor_msgs_ext` types I had made split things into different message groups that are easier to manage and transfer necessary data more efficiently.
> 
> If you do modify the source code to use `sensor_msgs/Imu`, I'd be willing to host it as a branch so others can use it when needed. Just let me know!

Thanks for your reply. I found [jeskesen/i2c_imu](https://github.com/jeskesen/i2c_imu) and published `sensor_msgs/Imu` successfully  .
